# Generated by Django 5.1.6 on 2025-04-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='nmeapp_blogs/'),
            preserve_default=False,
        ),
    ]
