# Generated by Django 5.1.6 on 2025-06-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='rate_limit',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
