# Generated by Django 5.1.6 on 2025-06-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_login_rate_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='rate_limit',
            field=models.IntegerField(default=0),
        ),
    ]
