# Generated by Django 5.1.6 on 2025-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_login_last_failed_login_alter_login_rate_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
