# Generated by Django 5.1.6 on 2025-06-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_login_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
