# Generated by Django 5.2.5 on 2026-01-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
