# Generated by Django 5.2.5 on 2026-01-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='sentence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
