# Generated by Django 5.2.5 on 2026-01-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_teammember_sentence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
