# Generated by Django 5.2.5 on 2026-01-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_delete_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('sentence', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
