# Generated by Django 5.2.5 on 2026-01-07 13:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
