# Generated by Django 5.2.5 on 2026-01-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
